server:
  port: 8087
#  servlet:
#    context-path: /gecko

###################  beetl配置  ###################
#beetl:
#  delimiter-statement-start: \@
#  delimiter-statement-end: null
#  resource-tag-root: common/tags
#  resource-tag-suffix: tag


###################  spring配置  ###################
spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: fastjson
  mvc:
    static-path-pattern: /static/**
#    view:
#      prefix: /WEB-INF/views
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  resources:
    static-locations: classpath:/static/
    chain:
      cache: true
      strategy:
        content:
          enabled: true

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:org/gecko/modular/code/mapper/*.xml
  typeAliasesPackage: org.gecko.modular.code.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
 #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
#########################  dev  ##########################
##########################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/gecko?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

mybatis-plus:
  global-config:
    refresh-mapper: true
#logging.level.org.apache.shiro=DEBUG
#jdbc.driver-class-name=org.gjt.mm.mysql.Driver
#jdbc.url=jdbc\:mysql\://10.6.168.10\:3306/ops_webconsole?useUnicode\=true&characterEncoding\=utf-8&autoReconnect\=true
#jdbc.username=ops
#jdbc.password=ops@#$
